services:
  psql-db:
    image: postgres
    container_name: lifedexdb
    restart: always
    environment:
      - POSTGRES_USER=lifedex
      - POSTGRES_PASSWORD=lifedex
      - POSTGRES_DB=lifedex
    ports:
      - '5432:5432'

  lifedex:
    container_name: lifedex
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/lifedex
      - SPRING_DATASOURCE_USERNAME=lifedex
      - SPRING_DATASOURCE_PASSWORD=lifedex
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db